tag_poses:
- frame_id: map
  id: 0
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.74
  y: 0.422
  z: -1.3
- frame_id: map
  id: 1
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.49
  y: 0.422
  z: -1.3
- frame_id: map
  id: 2
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.24
  y: 0.422
  z: -1.3
- frame_id: map
  id: 3
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.99
  y: 0.422
  z: -1.3
- frame_id: map
  id: 4
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.74
  y: 0.422
  z: -1.3
- frame_id: map
  id: 5
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.49
  y: 0.422
  z: -1.3
- frame_id: map
  id: 6
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.24
  y: 0.422
  z: -1.3
- frame_id: map
  id: 7
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.74
  y: 0.81575
  z: -1.3
- frame_id: map
  id: 8
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.49
  y: 0.81575
  z: -1.3
- frame_id: map
  id: 9
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.24
  y: 0.81575
  z: -1.3
- frame_id: map
  id: 10
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.99
  y: 0.81575
  z: -1.3
- frame_id: map
  id: 11
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.74
  y: 0.81575
  z: -1.3
- frame_id: map
  id: 12
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.49
  y: 0.81575
  z: -1.3
- frame_id: map
  id: 13
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.24
  y: 0.81575
  z: -1.3
- frame_id: map
  id: 14
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.74
  y: 1.2095
  z: -1.3
- frame_id: map
  id: 15
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.49
  y: 1.2095
  z: -1.3
- frame_id: map
  id: 16
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.24
  y: 1.2095
  z: -1.3
- frame_id: map
  id: 17
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.99
  y: 1.2095
  z: -1.3
- frame_id: map
  id: 18
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.74
  y: 1.2095
  z: -1.3
- frame_id: map
  id: 19
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.49
  y: 1.2095
  z: -1.3
- frame_id: map
  id: 20
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.24
  y: 1.2095
  z: -1.3
- frame_id: map
  id: 21
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.74
  y: 1.6032499999999998
  z: -1.3
- frame_id: map
  id: 22
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.49
  y: 1.6032499999999998
  z: -1.3
- frame_id: map
  id: 23
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.24
  y: 1.6032499999999998
  z: -1.3
- frame_id: map
  id: 24
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.99
  y: 1.6032499999999998
  z: -1.3
- frame_id: map
  id: 25
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.74
  y: 1.6032499999999998
  z: -1.3
- frame_id: map
  id: 26
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.49
  y: 1.6032499999999998
  z: -1.3
- frame_id: map
  id: 27
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.24
  y: 1.6032499999999998
  z: -1.3
- frame_id: map
  id: 28
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.74
  y: 1.9969999999999999
  z: -1.3
- frame_id: map
  id: 29
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.49
  y: 1.9969999999999999
  z: -1.3
- frame_id: map
  id: 30
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.24
  y: 1.9969999999999999
  z: -1.3
- frame_id: map
  id: 31
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.99
  y: 1.9969999999999999
  z: -1.3
- frame_id: map
  id: 32
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.74
  y: 1.9969999999999999
  z: -1.3
- frame_id: map
  id: 33
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.49
  y: 1.9969999999999999
  z: -1.3
- frame_id: map
  id: 34
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.24
  y: 1.9969999999999999
  z: -1.3
- frame_id: map
  id: 35
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.74
  y: 2.39075
  z: -1.3
- frame_id: map
  id: 36
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.49
  y: 2.39075
  z: -1.3
- frame_id: map
  id: 37
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.24
  y: 2.39075
  z: -1.3
- frame_id: map
  id: 38
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.99
  y: 2.39075
  z: -1.3
- frame_id: map
  id: 39
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.74
  y: 2.39075
  z: -1.3
- frame_id: map
  id: 40
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.49
  y: 2.39075
  z: -1.3
- frame_id: map
  id: 41
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.24
  y: 2.39075
  z: -1.3
- frame_id: map
  id: 42
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.74
  y: 2.7845
  z: -1.3
- frame_id: map
  id: 43
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.49
  y: 2.7845
  z: -1.3
- frame_id: map
  id: 44
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.24
  y: 2.7845
  z: -1.3
- frame_id: map
  id: 45
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.99
  y: 2.7845
  z: -1.3
- frame_id: map
  id: 46
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.74
  y: 2.7845
  z: -1.3
- frame_id: map
  id: 47
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.49
  y: 2.7845
  z: -1.3
- frame_id: map
  id: 48
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.24
  y: 2.7845
  z: -1.3
- frame_id: map
  id: 49
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.74
  y: 3.1782500000000002
  z: -1.3
- frame_id: map
  id: 50
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.49
  y: 3.1782500000000002
  z: -1.3
- frame_id: map
  id: 51
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.24
  y: 3.1782500000000002
  z: -1.3
- frame_id: map
  id: 52
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.99
  y: 3.1782500000000002
  z: -1.3
- frame_id: map
  id: 53
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.74
  y: 3.1782500000000002
  z: -1.3
- frame_id: map
  id: 54
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.49
  y: 3.1782500000000002
  z: -1.3
- frame_id: map
  id: 55
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.24
  y: 3.1782500000000002
  z: -1.3
- frame_id: map
  id: 56
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.74
  y: 3.572
  z: -1.3
- frame_id: map
  id: 57
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.49
  y: 3.572
  z: -1.3
- frame_id: map
  id: 58
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 1.24
  y: 3.572
  z: -1.3
- frame_id: map
  id: 59
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.99
  y: 3.572
  z: -1.3
- frame_id: map
  id: 60
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.74
  y: 3.572
  z: -1.3
- frame_id: map
  id: 61
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.49
  y: 3.572
  z: -1.3
- frame_id: map
  id: 62
  qw: 1.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  size: 0.096
  x: 0.24
  y: 3.572
  z: -1.3
